Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -71,7 +71,7 @@ jobs:
 
         - run:
             command: |  
-              count=60
+              count=2
               while [ ${count} -gt 0 ]; do
 
                 if [ -f /tmp/openvpn.log ] && [ "$(grep -c "Initialization Sequence Completed" /tmp/openvpn.log)" != 0 ]; then
@@ -83,6 +83,12 @@ jobs:
                   sleep 1
                 fi
               done
+
+              if ! [ -f /tmp/openvpn.log ] && [ "$(grep -c "Initialization Sequence Completed" /tmp/openvpn.log)" != 0 ]; then
+                echo "Connection to VPN failed "
+                exit 1
+              fi
+
             # name: Wait for the connection to be established and check IP  
             # command: |  
             #   until [ -f /tmp/openvpn.log ] && [ "$(grep -c "Initialization Sequence Completed" /tmp/openvpn.log)" != 0 ]; do  
